services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - grafana_local
    depends_on:
      - mysqld-exporter
    links:
      - mysqld-exporter
      - node-exporter

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - grafana_local

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./volumes/grafana-storage:/var/lib/grafana
    networks:
      - grafana_local
    links:
      - prometheus
    depends_on:
      - prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter
    command: --config.my-cnf=/cfg/.my.cnf
    environment:
      - "DATA_SOURCE_NAME=root${DB_PASSWORD}:@(mysql:3306)/"
    ports:
      - 9104:9104
    volumes:
      - ./config.my-cnf:/cfg/.my.cnf
    networks:
      - grafana_local
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    environment:
      TERM: linux
      LANG: 'C.UTF-8'
      LOG_ROTATION_DAY: 7
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    dns:
      - 1.1.1.1
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: '2'
    restart: 'no'
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-p${DB_PASSWORD}'
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./volumes/db/data:/var/lib/mysql:delegated
    networks:
      - grafana_local

networks:
  grafana_local:
    driver: bridge
