global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'mysql'
    params:
      auth_module: [client]
    scrape_interval: 5s
    static_configs:
      - targets: ['mysql:3306']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
          # The mysqld_exporter host:port
        replacement: mysqld-exporter:9104
  - job_name: 'mongodb-sniffer'
    static_configs:
      - targets: ['mongodb-exporter:9216']
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
